// <auto-generated />
using System;
using CoopTracker;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoopTracker.Migrations
{
    [DbContext(typeof(CoopTrackerDbContext))]
    partial class CoopTrackerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoopTracker.Data.GroupKeyMaster", b =>
                {
                    b.Property<int>("GroupKeyMasterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupKeyMasterId"));

                    b.Property<string>("HashGroup")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupKeyMasterId");

                    b.ToTable("GroupKeyMaster");
                });

            modelBuilder.Entity("CoopTracker.ProffApply", b =>
                {
                    b.Property<int>("ProffApplyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProffApplyId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupKeyMasterId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<int>("TrackeeId")
                        .HasColumnType("int");

                    b.HasKey("ProffApplyId");

                    b.HasIndex("GroupKeyMasterId");

                    b.HasIndex("TrackeeId");

                    b.ToTable("ProffApplys");
                });

            modelBuilder.Entity("CoopTracker.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupKeyMasterId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentGeorgianCoolegeId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StudentId");

                    b.HasIndex("GroupKeyMasterId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("CoopTracker.Trackee", b =>
                {
                    b.Property<int>("TrackeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackeeId"));

                    b.Property<string>("CompanyCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAppliation")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentProvided")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupKeyMasterId")
                        .HasColumnType("int");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TrackerId")
                        .HasColumnType("int");

                    b.HasKey("TrackeeId");

                    b.HasIndex("GroupKeyMasterId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TrackerId");

                    b.ToTable("Trackees");
                });

            modelBuilder.Entity("CoopTracker.Tracker", b =>
                {
                    b.Property<int>("TrackerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackerId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime2");

                    b.Property<int>("GroupKeyMasterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Start")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Submit")
                        .HasColumnType("datetime2");

                    b.HasKey("TrackerId");

                    b.HasIndex("GroupKeyMasterId");

                    b.ToTable("Trackers");
                });

            modelBuilder.Entity("CoopTracker.TrackerDetail", b =>
                {
                    b.Property<int>("TrackerDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrackerDetailId"));

                    b.Property<string>("CompanyCity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateAppliation")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentProvided")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GroupKeyMaster")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastUpdate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StudentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TrackerDetailId");

                    b.ToTable("TrackerDetails");
                });

            modelBuilder.Entity("CoopTracker.ProffApply", b =>
                {
                    b.HasOne("CoopTracker.Data.GroupKeyMaster", "GroupKeyMaster")
                        .WithMany("ProffApply")
                        .HasForeignKey("GroupKeyMasterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CoopTracker.Trackee", "Trackee")
                        .WithMany("ProffApply")
                        .HasForeignKey("TrackeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupKeyMaster");

                    b.Navigation("Trackee");
                });

            modelBuilder.Entity("CoopTracker.Student", b =>
                {
                    b.HasOne("CoopTracker.Data.GroupKeyMaster", "GroupKeyMaster")
                        .WithMany("Student")
                        .HasForeignKey("GroupKeyMasterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GroupKeyMaster");
                });

            modelBuilder.Entity("CoopTracker.Trackee", b =>
                {
                    b.HasOne("CoopTracker.Data.GroupKeyMaster", "GroupKeyMaster")
                        .WithMany("Trackee")
                        .HasForeignKey("GroupKeyMasterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CoopTracker.Student", "Student")
                        .WithMany("Trackee")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoopTracker.Tracker", "Tracker")
                        .WithMany("Trackee")
                        .HasForeignKey("TrackerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GroupKeyMaster");

                    b.Navigation("Student");

                    b.Navigation("Tracker");
                });

            modelBuilder.Entity("CoopTracker.Tracker", b =>
                {
                    b.HasOne("CoopTracker.Data.GroupKeyMaster", "GroupKeyMaster")
                        .WithMany("Tracker")
                        .HasForeignKey("GroupKeyMasterId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("GroupKeyMaster");
                });

            modelBuilder.Entity("CoopTracker.Data.GroupKeyMaster", b =>
                {
                    b.Navigation("ProffApply");

                    b.Navigation("Student");

                    b.Navigation("Trackee");

                    b.Navigation("Tracker");
                });

            modelBuilder.Entity("CoopTracker.Student", b =>
                {
                    b.Navigation("Trackee");
                });

            modelBuilder.Entity("CoopTracker.Trackee", b =>
                {
                    b.Navigation("ProffApply");
                });

            modelBuilder.Entity("CoopTracker.Tracker", b =>
                {
                    b.Navigation("Trackee");
                });
#pragma warning restore 612, 618
        }
    }
}
